# fly.toml app configuration file generated for fly-registry-api on 2024-12-01T17:18:59+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-template-api-project'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3100
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'
    path = '/health'
    protocol = 'http'
    tls_skip_verify = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  DOPPLER_CONFIG = 'prd'
  DEBUG = 'my-service:*'