/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos, and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2023 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 104 }


  /* === schema: public === */

  /* --- enums --- */
  /* (none) */

  /* --- tables --- */

  /**
   * **soup**
   * - Table in database
   */
  export namespace soup {
    export type Table = 'soup';
    export interface Selectable {
      /**
      * **soup.content**
      * - `jsonb` in database
      * - `NOT NULL`, no default
      */
      content: db.JSONValue;
      /**
      * **soup.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created_at: Date;
      /**
      * **soup.modified_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      modified_at: Date;
      /**
      * **soup.soup_group_id**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      soup_group_id: string;
      /**
      * **soup.soup_id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      soup_id: string;
      /**
      * **soup.soup_name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      soup_name: string;
    }
    export interface JSONSelectable {
      /**
      * **soup.content**
      * - `jsonb` in database
      * - `NOT NULL`, no default
      */
      content: db.JSONValue;
      /**
      * **soup.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created_at: db.TimestampTzString;
      /**
      * **soup.modified_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      modified_at: db.TimestampTzString;
      /**
      * **soup.soup_group_id**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      soup_group_id: string;
      /**
      * **soup.soup_id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      soup_id: string;
      /**
      * **soup.soup_name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      soup_name: string;
    }
    export interface Whereable {
      /**
      * **soup.content**
      * - `jsonb` in database
      * - `NOT NULL`, no default
      */
      content?: db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn>;
      /**
      * **soup.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **soup.modified_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      modified_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **soup.soup_group_id**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      soup_group_id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **soup.soup_id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      soup_id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **soup.soup_name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      soup_name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **soup.content**
      * - `jsonb` in database
      * - `NOT NULL`, no default
      */
      content: db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment;
      /**
      * **soup.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment;
      /**
      * **soup.modified_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      modified_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment;
      /**
      * **soup.soup_group_id**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      soup_group_id: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **soup.soup_id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      soup_id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **soup.soup_name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      soup_name: string | db.Parameter<string> | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **soup.content**
      * - `jsonb` in database
      * - `NOT NULL`, no default
      */
      content?: db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment>;
      /**
      * **soup.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment>;
      /**
      * **soup.modified_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      modified_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment>;
      /**
      * **soup.soup_group_id**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      soup_group_id?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **soup.soup_id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      soup_id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **soup.soup_name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      soup_name?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
    }
    export type UniqueIndex = 'soup_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **soup_group**
   * - Table in database
   */
  export namespace soup_group {
    export type Table = 'soup_group';
    export interface Selectable {
      /**
      * **soup_group.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created_at: Date;
      /**
      * **soup_group.soup_group_id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      soup_group_id: string;
      /**
      * **soup_group.soup_group_name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      soup_group_name: string;
    }
    export interface JSONSelectable {
      /**
      * **soup_group.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created_at: db.TimestampTzString;
      /**
      * **soup_group.soup_group_id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      soup_group_id: string;
      /**
      * **soup_group.soup_group_name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      soup_group_name: string;
    }
    export interface Whereable {
      /**
      * **soup_group.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **soup_group.soup_group_id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      soup_group_id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **soup_group.soup_group_name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      soup_group_name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **soup_group.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment;
      /**
      * **soup_group.soup_group_id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      soup_group_id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **soup_group.soup_group_name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      soup_group_name: string | db.Parameter<string> | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **soup_group.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment>;
      /**
      * **soup_group.soup_group_id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      soup_group_id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **soup_group.soup_group_name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      soup_group_name?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
    }
    export type UniqueIndex = 'soup_group_pkey' | 'soup_group_soup_group_name_key';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* --- aggregate types --- */

  export namespace public {  
    export type Table = soup.Table | soup_group.Table;
    export type Selectable = soup.Selectable | soup_group.Selectable;
    export type JSONSelectable = soup.JSONSelectable | soup_group.JSONSelectable;
    export type Whereable = soup.Whereable | soup_group.Whereable;
    export type Insertable = soup.Insertable | soup_group.Insertable;
    export type Updatable = soup.Updatable | soup_group.Updatable;
    export type UniqueIndex = soup.UniqueIndex | soup_group.UniqueIndex;
    export type Column = soup.Column | soup_group.Column;
  
    export type AllBaseTables = [soup.Table, soup_group.Table];
    export type AllForeignTables = [];
    export type AllViews = [];
    export type AllMaterializedViews = [];
    export type AllTablesAndViews = [soup.Table, soup_group.Table];
  }



  /* === global aggregate types === */

  export type Schema = 'public';
  export type Table = public.Table;
  export type Selectable = public.Selectable;
  export type JSONSelectable = public.JSONSelectable;
  export type Whereable = public.Whereable;
  export type Insertable = public.Insertable;
  export type Updatable = public.Updatable;
  export type UniqueIndex = public.UniqueIndex;
  export type Column = public.Column;

  export type AllSchemas = ['public'];
  export type AllBaseTables = [...public.AllBaseTables];
  export type AllForeignTables = [...public.AllForeignTables];
  export type AllViews = [...public.AllViews];
  export type AllMaterializedViews = [...public.AllMaterializedViews];
  export type AllTablesAndViews = [...public.AllTablesAndViews];


  /* === lookups === */

  export type SelectableForTable<T extends Table> = {
    "soup": soup.Selectable;
    "soup_group": soup_group.Selectable;
  }[T];

  export type JSONSelectableForTable<T extends Table> = {
    "soup": soup.JSONSelectable;
    "soup_group": soup_group.JSONSelectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    "soup": soup.Whereable;
    "soup_group": soup_group.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    "soup": soup.Insertable;
    "soup_group": soup_group.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    "soup": soup.Updatable;
    "soup_group": soup_group.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    "soup": soup.UniqueIndex;
    "soup_group": soup_group.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    "soup": soup.Column;
    "soup_group": soup_group.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    "soup": soup.SQL;
    "soup_group": soup_group.SQL;
  }[T];

}
